// <auto-generated />
namespace DIBZ.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmailTemplate_AND_EmailNotification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailTemplate_AND_EmailNotification));
        
        string IMigrationMetadata.Id
        {
            get { return "201801170729053_EmailTemplate_AND_EmailNotification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
