// <auto-generated />
namespace DIBZ.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB_Changes_For_FormatShortName_And_NewletterPhoneNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_Changes_For_FormatShortName_And_NewletterPhoneNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201801040725120_DB_Changes_For_FormatShortName_And_NewletterPhoneNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
